# Generated by Django 5.0.2 on 2024-03-25 22:22
import secrets

from django.db import migrations


def add_user(apps, schema_editor):

    User = apps.get_model('auth', 'User')
    password = secrets.token_hex(25)
    print(f'\nPassword for poirot: {password}')
    user = User.objects.create_user("poirot", 'poirot@example.com', password)
    user.save()

    password = secrets.token_hex(25)
    print(f'Password for admin: {password}')
    admin = User.objects.create_user("admin", "admin@example.com", password)
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_user)
    ]
